
### /
POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "email@email.cl",
    "username": "gcm",
    "password": "prueba",
    "phone": "+569 9876 5432"
}


### /
GET http://localhost:3000/

### /user
GET http://localhost:3000/user

### /register
POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "email@email.cl",
    "username": "gcm",
    "password": "prueba"
}

### /logout
GET http://localhost:3000/auth/logout

### /auth ok
POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "gcm",
    "password": "prueba1"
}

### /auth no ok
POST http://localhost:3000/auth/login

{
    "email": "email@email.com",
    "password": "prueba"
}