
### /
POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "email@email.cl",
    "username": "gcm",
    "password": "prueba",
    "phone": "+569 9876 5432"
}


### /
GET http://localhost:3000/

### /service
GET http://localhost:3000/service

### /create service
POST http://localhost:3000/services
content-type: application/json

{
    "service_type":"sepultacion",
    "service_date":"2003/07/25",
    "state":"NO ACTIVO",
    "name":"Nombre cliente",
    "address":"Direccion cliente",
    "phone":"+569 9876 5432",
    "email":"email@email.cl",
    "kindship":"parentezco"
}

### / ceremony
GET http://localhost:3000/ceremonies


### /create ceremony
POST http://localhost:3000/ceremonies
content-type: application/json

{
 "service_id": 1,
 "ceremony_type": "instalacion",
 "schedule_date": "2023/01/01",
 "schedule_time": "10:00",
 "executed": "0"
}

### /delete ceremony
DELETE  http://localhost:3000/ceremonies/15
content-type: application/json


### /user
GET http://localhost:3000/user

### /register
POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "email@email.cl",
    "username": "gcm",
    "password": "prueba",
}

### /logout
GET http://localhost:3000/auth/logout

### /auth ok
POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "gcm",
    "password": "prueba1"
}

### /auth no ok
POST http://localhost:3000/auth/login

{
    "email": "email@email.com",
    "password": "prueba"
}