
### /
POST https://express-api-rest-jpn0.onrender.com/auth/register
content-type: application/json

{
    "email": "email2@email.cl",
    "username": "gcm3",
    "password": "prueba"
}


### /
GET https://gcerda-express-mysql-dev.onrender.com/

### /user
GET https://gcerda-express-mysql-dev.onrender.com/user

### /register
POST https://gcerda-express-mysql-dev.onrender.com/auth/register
content-type: application/json

{
    "email": "email2@email.cl",
    "username": "gcm3",
    "password": "prueba"
}

### /logout
GET https://gcerda-express-mysql-dev.onrender.com/auth/logout

### /auth ok
POST https://gcerda-express-mysql-dev.onrender.com/auth/login
content-type: application/json

{
    "username": "gcm",
    "password": "prueba"
}

### /auth no ok
POST https://gcerda-express-mysql-dev.onrender.com/auth/login

{
    "email": "email@email.com",
    "password": "prueba"
}