### /
GET https://express-api-rest-jpn0.onrender.com/

### /user
GET https://express-api-rest-jpn0.onrender.com/user

### /register
POST https://express-api-rest-jpn0.onrender.com/auth/register
content-type: application/json

{
    "email": "email@email.cl",
    "phone": "+569 9876 5432",
    "username": "gcm",
    "password": "prueba"
}

### /logout
GET https://express-api-rest-jpn0.onrender.com/auth/logout

### /auth ok
POST https://express-api-rest-jpn0.onrender.com/auth/login
content-type: application/json

{
    "username": "gcm",
    "password": "prueba2"
}

### /auth no ok
POST https://express-api-rest-jpn0.onrender.com/auth/login

{
    "email": "email@email.com",
    "password": "prueba"
}